import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import LoginModal from "./components/modals/LoginModal";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content =  (
      <p>Yo yo</p>
  )
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <Navbar />
        <div className="pt-32">
          {children}
        </div>
        <LoginModal />
      </body>
    </html>
  );
}
